### ISSUE TITLE
目标的标签分布估计输出都是0

### ISSUE THREAD

**Issue by PhDCJojo** [manmanjun/Undoing_UDA#1]
您好，请问在运行python test_trainlabelfre.py -cfg configs/deeplabv2_r101_adv.yaml resume g2c_adv.pth代码之后，目标的标签分布估计输出为什么都是0

**Comment by manmanjun** [comment]
我在我这边看是有输出的，这个代码需要遍历一边目标域的训练集，应该会需要15分钟时间。我猜测输出0的原因是因为你那边的数据集没有按照路径配置好。如果不是这个原因的话，可以在[134行](https://github.com/manmanjun/Undoing_UDA/blob/main/test_trainlabelfre.py#L134)后面print一下class_cout。
